version: "3.9"
services:
  api:
    build: .
    ports: ["8000:8000"]
    env_file: .env
    depends_on: ["redis"]
    volumes:
      - ./:/app
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
